#!/bin/bash
# setup-watch.sh — Register cron job for periodic watch checks
# Usage: ./scripts/setup-watch.sh [--interval 6]

set -euo pipefail

INTERVAL=${2:-6}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CRON_FILE="/etc/cron.d/huntmcp-watch"

# Determine which python to use
PYTHON="${PROJECT_DIR}/.venv/bin/python"
if [ ! -f "$PYTHON" ]; then
    PYTHON="python3"
fi

echo "Setting up HuntMCP watch cron (interval: ${INTERVAL}h)..."
echo "  Project: $PROJECT_DIR"
echo "  Python: $PYTHON"
echo "  Cron file: $CRON_FILE"

# Create the cron entry
# The watch check works by calling watch-mcp's own check_target() for each
# watched target directly (not a reimplementation) — that's what wires in
# the engagement.yaml scope check and tool_resolver's reactive rate-limit
# handling automatically, and keeps the cron path from drifting out of sync
# with the real MCP tool logic.
cat > /tmp/huntmcp-watch-cron.sh << 'WRAPPER'
#!/bin/bash
# huntmcp-watch-cron.sh — Check all active watched targets
# This is installed by setup-watch.sh and called by cron.

set -euo pipefail
PROJECT_DIR="{{PROJECT_DIR}}"
DB="${PROJECT_DIR}/data/watch.db"
PYTHON="{{PYTHON}}"
LOG="${PROJECT_DIR}/logs/watch-cron.log"
mkdir -p "$(dirname "$LOG")"

if [ ! -f "$DB" ]; then
    exit 0
fi

echo "[$(date)] Watch cron: checking targets..." >> "$LOG"

cd "$PROJECT_DIR"
"$PYTHON" -c "
import sqlite3
import sys
import time
sys.path.insert(0, 'mcp-servers/watch-mcp')
import server

server.init_db()
conn = sqlite3.connect(server.DB_PATH)
targets = [r[0] for r in conn.execute('SELECT target FROM watched_targets WHERE active = 1')]
conn.close()

# check_target() now backgrounds its work on a daemon thread and returns a
# job_id immediately (mcp-servers/job_runtime.py's thread-job mechanism --
# subfinder->httpx->katana chained can take longer than an MCP client's
# own per-call timeout). Daemon threads are killed outright the instant
# this one-shot process's main thread exits, with zero chance to finish --
# unlike an interactive MCP session (where an agent stays around to poll
# check_status()), this cron wrapper has nothing else to do anyway, so it
# explicitly waits for each job here instead of firing check_target() and
# exiting, which would otherwise silently stop continuous monitoring from
# ever completing a single real check.
for t in targets:
    print(f'--- {t} ---')
    start_msg = server.check_target(t)
    print(start_msg)
    if 'job_id=\"' in start_msg:
        job_id = start_msg.split('job_id=\"')[1].split('\"')[0]
        # Generous ceiling: subfinder/httpx/katana are each individually
        # timeout-bounded at 120s inside check_target(), so ~360s is the
        # real worst case -- this just needs to be comfortably above that.
        deadline = time.time() + 600
        result = server.check_status(job_id)
        while 'Still running' in result and time.time() < deadline:
            time.sleep(5)
            result = server.check_status(job_id)
        print(result)
" >> "$LOG" 2>&1

echo "[$(date)] Watch cron: done." >> "$LOG"
WRAPPER

# Replace placeholders
sed -i "s|{{PROJECT_DIR}}|$PROJECT_DIR|g" /tmp/huntmcp-watch-cron.sh
sed -i "s|{{PYTHON}}|$PYTHON|g" /tmp/huntmcp-watch-cron.sh
chmod +x /tmp/huntmcp-watch-cron.sh

# Install to project scripts dir
cp /tmp/huntmcp-watch-cron.sh "${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh"
rm -f /tmp/huntmcp-watch-cron.sh

# Attempt to install cron entry (may require sudo)
if [ -w "$(dirname "$CRON_FILE")" ]; then
    cat > "$CRON_FILE" << CRON
# HuntMCP Watch — Auto-generated by setup-watch.sh
# Check all watched targets every ${INTERVAL} hours
0 */${INTERVAL} * * * root ${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh
CRON
    echo "Cron installed at $CRON_FILE"
else
    echo "Note: Cannot write to $CRON_FILE (need sudo)."
    echo "To install manually, add to crontab:"
    echo ""
    echo "  0 */${INTERVAL} * * * ${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh"
    echo ""
    echo "Or run: sudo ./scripts/setup-watch.sh"
fi

echo ""
echo "Watch cron setup complete!"
echo "Manual setup reminder:"
echo "  1. Start watching: opencode run \"/watch start example.com\""
echo "  2. Check manually:  opencode run \"/watch check example.com\""
echo "  3. View history:    opencode run \"/watch history example.com\""
