#!/bin/bash
# setup-watch.sh — Register cron job for periodic watch checks
# Usage: ./scripts/setup-watch.sh [--interval 6]

set -euo pipefail

INTERVAL=${2:-6}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CRON_FILE="/etc/cron.d/huntmcp-watch"

# Determine which python to use
PYTHON="${PROJECT_DIR}/.venv/bin/python"
if [ ! -f "$PYTHON" ]; then
    PYTHON="python3"
fi

WATCH_MCP_SERVER="${PROJECT_DIR}/mcp-servers/watch-mcp/server.py"

echo "Setting up HuntMCP watch cron (interval: ${INTERVAL}h)..."
echo "  Project: $PROJECT_DIR"
echo "  Python: $PYTHON"
echo "  Cron file: $CRON_FILE"

# Create the cron entry
# The watch check works by calling watch-mcp's check_target for each watched target.
# Since MCP servers can't be called directly from cron, we use a wrapper that
# connects to the watch database directly.
cat > /tmp/huntmcp-watch-cron.sh << 'WRAPPER'
#!/bin/bash
# huntmcp-watch-cron.sh — Check all active watched targets
# This is installed by setup-watch.sh and called by cron.

set -euo pipefail
PROJECT_DIR="{{PROJECT_DIR}}"
DB="${PROJECT_DIR}/data/watch.db"
PYTHON="{{PYTHON}}"

if [ ! -f "$DB" ]; then
    exit 0
fi

# Get all active targets
TARGETS=$($PYTHON -c "
import sqlite3, sys
conn = sqlite3.connect('$DB')
rows = conn.execute('SELECT target FROM watched_targets WHERE active = 1').fetchall()
conn.close()
for r in rows:
    print(r[0])
" 2>/dev/null)

if [ -z "$TARGETS" ]; then
    exit 0
fi

echo "[$(date)] Watch cron: checking targets..."
LOG="${PROJECT_DIR}/logs/watch-cron.log"
mkdir -p "$(dirname "$LOG")"

echo "$TARGETS" | while read -r target; do
    echo "[$(date)] Checking $target..." >> "$LOG"
    # We can just log and let opencode handle it, or use subfinder/httpx directly
    $PYTHON -c "
import sqlite3, json, subprocess, sys
conn = sqlite3.connect('$DB')
# Count new subdomains since last snapshot
row = conn.execute('SELECT data FROM snapshots WHERE target = ? ORDER BY id DESC LIMIT 1', ('$target',)).fetchone()
previous = set(json.loads(row['data'])['subdomains']) if row else set()

result = subprocess.run(['subfinder', '-d', '$target', '-silent'], capture_output=True, text=True, timeout=120)
current = set(result.stdout.strip().splitlines()) if result.stdout.strip() else set()
new = current - previous
if new:
    print(f'$target: {len(new)} new subdomain(s): {', '.join(sorted(new))}')
    conn.execute('INSERT INTO watch_events (target, event_type, description, severity, details) VALUES (?, ?, ?, ?, ?)',
        ('$target', 'new_subdomain', f'{len(new)} new subdomain(s) found', 'medium', json.dumps({'subdomains': list(new)})))
conn.commit()
conn.close()
" 2>> "$LOG" || true
done

echo "[$(date)] Watch cron: done." >> "$LOG"
WRAPPER

# Replace placeholders
sed -i "s|{{PROJECT_DIR}}|$PROJECT_DIR|g" /tmp/huntmcp-watch-cron.sh
sed -i "s|{{PYTHON}}|$PYTHON|g" /tmp/huntmcp-watch-cron.sh
chmod +x /tmp/huntmcp-watch-cron.sh

# Install to project scripts dir
cp /tmp/huntmcp-watch-cron.sh "${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh"
rm -f /tmp/huntmcp-watch-cron.sh

# Attempt to install cron entry (may require sudo)
if [ -w "$(dirname "$CRON_FILE")" ]; then
    cat > "$CRON_FILE" << CRON
# HuntMCP Watch — Auto-generated by setup-watch.sh
# Check all watched targets every ${INTERVAL} hours
0 */${INTERVAL} * * * root ${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh
CRON
    echo "Cron installed at $CRON_FILE"
else
    echo "Note: Cannot write to $CRON_FILE (need sudo)."
    echo "To install manually, add to crontab:"
    echo ""
    echo "  0 */${INTERVAL} * * * ${PROJECT_DIR}/scripts/huntmcp-watch-cron.sh"
    echo ""
    echo "Or run: sudo ./scripts/setup-watch.sh"
fi

echo ""
echo "Watch cron setup complete!"
echo "Manual setup reminder:"
echo "  1. Start watching: opencode run \"/watch start example.com\""
echo "  2. Check manually:  opencode run \"/watch check example.com\""
echo "  3. View history:    opencode run \"/watch history example.com\""
