#!/bin/bash
# setup-bounty-scope-watch.sh — Register cron job for Tier 1 continuous
# bounty-scope discovery (ARCHITECTURE.md's "Continuous bounty-scope
# discovery" row). This is the CHEAP tier only: refresh_bounty_scope() +
# list_new_bounty_scope() just diff a handful of small JSON downloads
# against the previous snapshot -- no target is ever touched, safe to run
# on any reasonable cadence. It does NOT trigger any recon/scan against
# newly-discovered scope; that stays a deliberate, manual decision (see
# scripts/check-new-bounty-scope.sh for the read side of that decision).
#
# Usage: ./scripts/setup-bounty-scope-watch.sh [--interval-hours 1]
set -euo pipefail

INTERVAL_HOURS=1
if [ "${1:-}" = "--interval-hours" ] && [ -n "${2:-}" ]; then
    INTERVAL_HOURS="$2"
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CRON_FILE="/etc/cron.d/huntmcp-bounty-scope"

PYTHON="${PROJECT_DIR}/.venv/bin/python"
if [ ! -f "$PYTHON" ]; then
    PYTHON="python3"
fi

echo "Setting up HuntMCP bounty-scope discovery cron (interval: ${INTERVAL_HOURS}h)..."
echo "  Project: $PROJECT_DIR"
echo "  Python: $PYTHON"
echo "  Cron file: $CRON_FILE"

cat > /tmp/huntmcp-bounty-scope-cron.sh << 'WRAPPER'
#!/bin/bash
# huntmcp-bounty-scope-cron.sh — Tier 1 only: refresh + diff the aggregated
# bounty-scope cache. Installed by setup-bounty-scope-watch.sh, called by
# cron. Never touches a live target -- see bounty_scope.py's module
# docstring for why that split matters.

set -euo pipefail
PROJECT_DIR="{{PROJECT_DIR}}"
PYTHON="{{PYTHON}}"
LOG="${PROJECT_DIR}/logs/bounty-scope-cron.log"
mkdir -p "$(dirname "$LOG")"

echo "[$(date)] Bounty-scope cron: refreshing..." >> "$LOG"

cd "$PROJECT_DIR"
"$PYTHON" -c "
import sys
sys.path.insert(0, 'mcp-servers')
import bounty_scope

result = bounty_scope.refresh()
print(f'refresh: {result}')

if result.get('refreshed') and result.get('added', 0) > 0:
    new = bounty_scope.list_new_scope(since_hours=1)
    print(f'{len(new)} new scope entr{\"y\" if len(new) == 1 else \"ies\"} in the last hour:')
    for e in new:
        print(f'  [{e[\"platform\"]}] {e[\"domain\"]} -- {e[\"program\"]}')
" >> "$LOG" 2>&1

echo "[$(date)] Bounty-scope cron: done." >> "$LOG"
WRAPPER

sed -i "s|{{PROJECT_DIR}}|$PROJECT_DIR|g" /tmp/huntmcp-bounty-scope-cron.sh
sed -i "s|{{PYTHON}}|$PYTHON|g" /tmp/huntmcp-bounty-scope-cron.sh
chmod +x /tmp/huntmcp-bounty-scope-cron.sh

cp /tmp/huntmcp-bounty-scope-cron.sh "${PROJECT_DIR}/scripts/huntmcp-bounty-scope-cron.sh"
rm -f /tmp/huntmcp-bounty-scope-cron.sh

if [ -w "$(dirname "$CRON_FILE")" ]; then
    cat > "$CRON_FILE" << CRON
# HuntMCP bounty-scope discovery — Auto-generated by setup-bounty-scope-watch.sh
# Tier 1 only (refresh + diff, no target ever touched) — every ${INTERVAL_HOURS}h
0 */${INTERVAL_HOURS} * * * root ${PROJECT_DIR}/scripts/huntmcp-bounty-scope-cron.sh
CRON
    echo "Cron installed at $CRON_FILE"
else
    echo "Note: Cannot write to $CRON_FILE (need sudo)."
    echo "To install manually, add to crontab:"
    echo ""
    echo "  0 */${INTERVAL_HOURS} * * * ${PROJECT_DIR}/scripts/huntmcp-bounty-scope-cron.sh"
    echo ""
    echo "Or run: sudo ./scripts/setup-bounty-scope-watch.sh"
fi

echo ""
echo "Bounty-scope discovery cron setup complete!"
echo "Reminder: this only refreshes and diffs -- it never scans a target."
echo "  Check what's new anytime:  scripts/check-new-bounty-scope.sh"
echo "  Look up a specific domain: scripts/check-new-bounty-scope.sh lookup <domain>"
